lunetics_locale:
    allowed_locales:
        - es
    strict_mode: true # defaults to false
    guessing_order:
        - query
        - router
        - session
        - cookie
    switcher:
        show_current_locale: true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Pequiven\SEIPBundle\Entity\User
    registration:
        form:
            type: pequiven_seip_user_registration
    profile:
        form:
            type: pequiven_seip_user_profile
    group:
        group_class: Pequiven\MasterBundle\Entity\Rol
        group_manager: sonata.user.orm.group_manager
        form:
            type: seip_user_group
    service:
        user_manager: sonata.user.orm.user_manager

fos_rest:
    service:
        serializer: tpg_extjs.serializer
    allowed_methods_listener: true
    routing_loader:
        default_format: json
    view:
        view_response_listener: force
    access_denied_listener:
        # all requests using the 'json' format will return a 403 on an access denied violation
        json: true
    param_fetcher_listener: true
        
sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
