Pequiven\SEIPBundle\Entity\Sip\NominaCentro:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        Nombre:
            expose: true
            groups: [api_list]
        cedula:
            expose: true
            groups: [api_list]
        telefono:
            expose: true
            groups: [api_list]
        codigoCentro:
            expose: true
            groups: [api_list]
        Centro:
            expose: true
            groups: [api_list]