Pequiven\SEIPBundle\Model\BaseModel:
    exclusion_policy: ALL
    properties:
        createdAt:
            expose: true
            groups: [api_list]
        updatedAt:
            expose: true
            groups: [api_list]