Pequiven\ArrangementProgramBundle\Model\ArrangementProgram:
    exclusion_policy: ALL
    properties:
        type:
            expose: true
            groups: [api_list]
        period:
            expose: true
            groups: [period]
        categoryArrangementProgram:
            expose: true
            groups: [categoryArrangementProgram]
        managementSystem:
            expose: true
            groups: [managementSystem]