Pequiven\ArrangementProgramBundle\Model\ArrangementProgram:
    exclusion_policy: ALL
    properties:
        type:
            expose: true
            groups: [api_list]
        period:
            expose: true
            groups: [period]
        categoryArrangementProgram:
            expose: true
            groups: [categoryArrangementProgram]
        managementSystems:
            expose: true
            groups: [managementSystems]
        indicators:
            expose: true
            groups: [indicators]
        typeAction:
            expose: true
            groups: [typeAction]