#- Import the bundle's routing resource in the app main routing file:
#
#    TecnocreacionesBoxBundle:
#        resource: "@TecnocreacionesBoxBundle/Resources/config/routing.yml"
#        prefix:   /

tecnocreaciones_box_index:
    path:     /
    defaults: { _controller: TecnocreacionesBoxBundle:Box:index }
    
tecnocreaciones_box_add:
    path:     /add
    defaults: { _controller: TecnocreacionesBoxBundle:Box:add }