parameters:
#    tecnocreaciones_box.example.class: Tecnocreaciones\Bundle\BoxBundle\Example
    tecnocreaciones_box.render.class: Tecnocreaciones\Bundle\BoxBundle\Service\BoxRender

services:
#    tecnocreaciones_box.example:
#        class: %tecnocreaciones_box.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    tecnocreaciones_box.render:
        class: %tecnocreaciones_box.render.class%
        calls:
            - [setContainer,[@service_container]]