parameters:
    tecnocreaciones_box.render.class: Tecnocreaciones\Bundle\BoxBundle\Service\BoxRender
    tecnocreaciones_box.area_render.class: Tecnocreaciones\Bundle\BoxBundle\Service\AreaRender

services:
    tecnocreaciones_box.render:
        class: %tecnocreaciones_box.render.class%
        calls:
            - [setContainer,[@service_container]]
    tecnocreaciones_box.area.render:
        class: %tecnocreaciones_box.area_render.class%
        calls:
            - [setContainer,[@service_container]]
            - [setBoxRender,[@tecnocreaciones_box.render]]
    twig.extension.tecnocreaciones.render:
        class: Tecnocreaciones\Bundle\BoxBundle\Twig\Extension\BoxBundleExtension
        public: false
        tags:
            - { name: twig.extension }
        calls:
            - [setContainer,[@service_container]]