## SIP
pequiven_onePerTen_create:
    path: /create
    defaults:
        _controller: pequiven.controller.onePerTen:createAction
    methods: [GET|POST]
    options:
        expose: true

pequiven_sip_cutl_list:
    path: /cutl/list/.{_format}
    defaults:
        _controller: pequiven.controller.cutl:listAction
        _format: html
    requirements:
        _format: html|json|xml        
    methods: [GET]
pequiven_sip_cutl_show:
    path: /cult/{id}
    defaults:
        _controller: pequiven.controller.cutl:showAction
    methods: [GET|POST]
    options:
        expose: true
