## SIP
pequiven_onePerTen_create:
    path: /1x10/create
    defaults:
        _controller: pequiven.controller.onePerTen:createAction
    methods: [GET|POST]
    options:
        expose: true
        
search_one_por_cedula:
    path: /sip/search_one_per_cedula
    defaults:
        _controller: pequiven.controller.onePerTen:searchAction
    

pequiven_sip_cutl_list:
    path: /cutl/list/.{_format}
    defaults:
        _controller: pequiven.controller.cutl:listAction
        _format: html
    requirements:
        _format: html|json|xml        
    methods: [GET]

