## SIP
pequiven_onePerTen_create:
    path: /1x10/create
    defaults:
        _controller: pequiven.controller.onePerTen:createAction
    methods: [GET|POST]
    options:
        expose: true
        
search_one_por_cedula:
    path: /sip/search_one_per_cedula
    defaults:
        _controller: pequiven.controller.onePerTen:searchAction
        
update_assistance_cutl:
    path: /sip/update
    defaults:
        _controller: pequiven.controller.cutl:updateAssistance
    
pequiven_sip_cutl_list:
    path: /cutl/list.{_format}
    defaults:
        _controller: pequiven.controller.cutl:listAction
        _format: html
    requirements:
        _format: html|json|xml        
    methods: [GET]
    
pequiven_sip_cutl_show:
    path: /cult/{id}
    defaults:
        _controller: pequiven.controller.cutl:showAction
    methods: [GET|POST]
    options:
        expose: true
#Centro 
pequiven_sip_center_observations:    
    path: /center/get-form_add.{_format}
    defaults:
        _controller: pequiven.controller.center:formObservationsAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
#Guardamos el formulario de las observaciones
pequiven_sip_center_observations_add:
    path: /center/addObservations.{_format}
    defaults:
        _controller: pequiven.controller.center:addObservationsAction
        _format: json
    requirements:
        _format: json
    methods: [POST]
    options:
        expose: true
        
pequiven_sip_center_list:
    path: /center/list.{_format}
    defaults:
        _controller: pequiven.controller.center:listAction
        _format: html
    requirements:
        _format: html|json|xml        
    methods: [GET]

pequiven_sip_center_show:
    path: /center/{id}
    defaults:
        _controller: pequiven.controller.center:showAction
    methods: [GET|POST]
    options:
        expose: true