## SIP
pequiven_onePerTen_create:
    path: /create
    defaults:
        _controller: pequiven.controller.onePerTen:createAction
    methods: [GET|POST]
    options:
        expose: true

pequiven_sip_cutl_list:
    path: /cutl/list
    defaults:
        _controller: pequiven.controller.cutl:listAction
    methods: [GET|POST]
    options:
        expose: true
