## SIP
pequiven_onePerTen_add_member:
    path: /1x10/add/{idUserOne}
    defaults:
        _controller: pequiven.controller.onePerTen:addMemberAction
    methods: [GET|POST]
    options:
        expose: true
        
search_one_por_cedula:
    path: /sip/search_one_per_cedula
    defaults:
        _controller: pequiven.controller.onePerTen:searchAction
        
update_assistance_cutl:
    path: /sip/update
    defaults:
        _controller: pequiven.controller.cutl:updateAssistance
    
pequiven_sip_cutl_list:
    path: /cutl/list.{_format}
    defaults:
        _controller: pequiven.controller.cutl:listAction
        _format: html
    requirements:
        _format: html|json|xml        
    methods: [GET]
    
pequiven_sip_cutl_show:
    path: /cult/{id}
    defaults:
        _controller: pequiven.controller.cutl:showAction
    methods: [GET|POST]
    options:
        expose: true

        
save_onePerTen:
    path: /1x10/save
    defaults:
        _controller: pequiven.controller.onePerTen:saveAction
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_search_members:
    path: /1x10/search
    defaults:
        _controller: pequiven.controller.onePerTen:searchMembersAction
        
pequiven_delete_member:
    path: /1x10/delMember
    defaults:
        _controller: pequiven.controller.onePerTen:deleteMemeberAction
    

#Centro 
pequiven_sip_center_observations:    
    path: /{idCenter}/get-form_add.{_format}
    defaults:
        _controller: pequiven.controller.center:formObservationsAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
#Revisión Cambio de status
pequiven_sip_center_observations_status:    
    path: /{idObs}/get-status_add.{_format}
    defaults:
        _controller: pequiven.controller.center:formStatusAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true


#Guardamos el formulario de las observaciones
pequiven_sip_center_observations_add:
    path: /{idCenter}/addObservations.{_format}
    defaults:
        _controller: pequiven.controller.center:addObservationsAction
        _format: json
    requirements:
        _format: json
    methods: [POST]
    options:
        expose: true
#Guardamos la revisión
pequiven_sip_center_observations_add_status:
    path: /{idObs}/addStatus.{_format}
    defaults:
        _controller: pequiven.controller.center:formStatusAction
        _format: json
    requirements:
        _format: json
    methods: [POST]
    options:
        expose: true
#Eliminacion de Observación
pequiven_sip_center_observations_delete:
    path: /{id}/delObservations.{_format}
    defaults:
        _controller: pequiven.controller.center:delObservationsAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
#Asistencia
pequiven_sip_center_assists:
    path: /{idCenter}/assists.{_format}
    defaults:
        _controller: pequiven.controller.center:formAssistsAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
#Guardamos el formulario de las asistencias
pequiven_sip_center_assists_add:
    path: /{idCenter}/addAssists.{_format}
    defaults:
        _controller: pequiven.controller.center:addAssistsAction
        _format: json
    requirements:
        _format: json
    methods: [POST]
    options:
        expose: true
#Eliminacion de Asistencias
pequiven_sip_center_assists_delete:
    path: /{id}/delAssists.{_format}
    defaults:
        _controller: pequiven.controller.center:delAssistsAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
#Inventario
pequiven_sip_center_inventory:
    path: /{idCenter}/inventory.{_format}
    defaults:
        _controller: pequiven.controller.center:formInventoryAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
#Guardamos el formulario del inventario
pequiven_sip_center_inventory_add:
    path: /{idCenter}/addInventory.{_format}
    defaults:
        _controller: pequiven.controller.center:formInventoryAction
        _format: json
    requirements:
        _format: json
    methods: [POST]
    options:
        expose: true
#Eliminacion de Inventario
pequiven_sip_center_inventory_delete:
    path: /{id}/delInventory.{_format}
    defaults:
        _controller: pequiven.controller.center:delInventoryAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
pequiven_sip_center_list:
    path: /center/list.{_format}
    defaults:
        _controller: pequiven.controller.center:listAction
        _format: html
    requirements:
        _format: html|json|xml        
    methods: [GET]
pequiven_sip_center_show:
    path: /center/{id}
    defaults:
        _controller: pequiven.controller.center:showAction
    methods: [GET|POST]
    options:
        expose: true