## SIP
pequiven_onePerTen_add_member:
    path: /1x10/add/{idUserOne}
    defaults:
        _controller: pequiven.controller.onePerTen:addMemberAction
    methods: [GET|POST]
    options:
        expose: true
        
search_one_por_cedula:
    path: /sip/search_one_per_cedula
    defaults:
        _controller: pequiven.controller.onePerTen:searchAction
        
update_assistance_cutl:
    path: /sip/update
    defaults:
        _controller: pequiven.controller.cutl:updateAssistance
    
pequiven_sip_cutl_list:
    path: /cutl/list.{_format}
    defaults:
        _controller: pequiven.controller.cutl:listAction
        _format: html
    requirements:
        _format: html|json|xml        
    methods: [GET]
    
pequiven_sip_cutl_show:
    path: /cult/{id}
    defaults:
        _controller: pequiven.controller.cutl:showAction
    methods: [GET|POST]
    options:
        expose: true
        
save_onePerTen:
    path: /1x10/save
    defaults:
        _controller: pequiven.controller.onePerTen:saveAction
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_search_members:
    path: /1x10/search
    defaults:
        _controller: pequiven.controller.onePerTen:searchMembersAction
        
pequiven_delete_member:
    path: /1x10/delMember
    defaults:
        _controller: pequiven.controller.onePerTen:deleteMemeberAction
    

