## SIP
pequiven_onePerTen_create:
    path: /create
    defaults:
        _controller: pequiven.controller.onePerTen:createAction
    methods: [GET|POST]
    options:
        expose: true
pequiven_cutl_list:
    path: /cutl/list
    defaults:
        _controller: pequiven.controller.onePerTen:listCutlAction
    methods: [GET|POST]
    options:
        expose: true
