## SIP
pequiven_onePerTen_create:
    path: /1x10/create
    defaults:
        _controller: pequiven.controller.onePerTen:createAction
    methods: [GET|POST]
    options:
        expose: true
        
search_one_por_cedula:
    path: /sip/search_one_per_cedula
    defaults:
        _controller: pequiven.controller.onePerTen:searchAction
    