pequiven_indicator:
    resource: "@PequivenIndicatorBundle/Controller/"
    type:     annotation
    prefix:   /indicator

pequiven_master:
    resource: "@PequivenMasterBundle/Controller/"
    type:     annotation
    prefix:   /master

pequiven_objetive:
    resource: "@PequivenObjetiveBundle/Controller/"
    type:     annotation
    prefix:   /objetive

pequiven_seip:
    resource: "@PequivenSEIPBundle/Controller/"
    type:     annotation
    prefix:   /

tecnocreaciones_template:
    resource: "@TecnocreacionesTemplateBundle/Controller/"
    type:     annotation
    prefix:   /

pequiven_seip_menu:
    resource: "@PequivenSEIPBundle/Resources/config/routing/menu.yml"
    
pequiven_objetive_route:
    resource: "@PequivenObjetiveBundle/Resources/config/routing/routing.yml"

pequiven_indicator_route:
    resource: "@PequivenIndicatorBundle/Resources/config/routing/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"    
    
ext_direct:
    resource: "@ExtDirectBundle/Resources/config/routing.yml"