security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    acl:
        connection: default
    role_hierarchy:
        ROLE_VIEW: [ROLE_WORKER_PQV,ROLE_WORKER_PLANNING]
        ROLE_ADMIN: ROLE_DIRECTIVE,ROLE_DIRECTIVE_AUX,ROLE_MANAGER_FIRST,ROLE_MANAGER_FIRST_AUX,ROLE_MANAGER_SECOND,ROLE_MANAGER_SECOND_AUX,ROLE_SUPERVISER,ROLE_WORKER_PQV,ROLE_VIEW,ROLE_SONATA_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern: ^/(login$|register|resetting)
            anonymous: ~
        cache:
            pattern: ^/media/cache
            security: false
        main:
            pattern: ^/
            anonymous: false
            switch_user: { role: ROLE_SUPER_ADMIN }
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
                
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
            anonymous:          true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            
             # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        
        - { path: ^/planning/, role: ROLE_WORKER_PLANNING }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
