security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_VIEW: ROLE_WORKER_PQV
        ROLE_ADMIN: ROLE_DIRECTIVE,ROLE_DIRECTIVE_AUX,ROLE_MANAGER_FIRST,ROLE_MANAGER_FIRST_AUX,ROLE_MANAGER_SECOND,ROLE_MANAGER_SECOND_AUX,ROLE_SUPERVISER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern: ^/(login$|register|resetting)
            anonymous: ~
        cache:
            pattern: ^/media/cache
            security: false
        main:
            pattern: ^/
            anonymous: false
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
