pequiven_report_template_delivery_index:
    path: /.{_format}
    defaults:
        _controller: pequiven.controller.report_template_delivery:indexAction
        _format: html
    requirements:
        _format: json|html
    methods: [GET]
    