## YAML Template.
pequiven_objetive_home:
    path: /objetive
    defaults: {_controller: PequivenObjetiveBundle:Objetive:index}

pequiven_objetive_list:
    path: /objetive/list
    defaults: {_controller: PequivenObjetiveBundle:Objetive:list}
    
verify_objetiveLevel:
    path: /arrangement/objetive/verifyObjetiveLevel
    defaults: {_controller: PequivenObjetiveBundle:Objetive:verifyObjetiveLevel}