#Ficha del indicador
pequiven_indicator_show:
    path: /{id}.{_format}
    defaults:
        _controller: pequiven.controller.indicator:showAction
        _format: html
    requirements:
        _format: html|json|xml
        id: \d+
    methods: [GET]
    
#Vista de los Indicadores Hijos
pequiven_indicator_show_dashboard:
    path: /{id}/dashboard.{_format}
    defaults:
        _controller: pequiven.controller.indicator:showDashboardAction
        _format: html
    requirements:
        _format: html|json|xml
        id: \d+
    methods: [GET]
    
pequiven_indicator_list:
    path: /{level}/list.{_format}
    defaults:
        _controller: pequiven.controller.indicator:listAction
        _format: html
    requirements:
        _format: html|json|xml
        level: 1|2|3
    methods: [GET]
    
pequiven_indicator_add_observation:
    path: /{id}/add-observation.{_format}
    defaults:
        _controller: pequiven.controller.indicator:addObservationAction
        _format: html
    requirements:
        _format: html
        id: \d+
    methods: [POST]
    
pequiven_indicator_remove_values:
    path: /{id}/remove-values
    defaults:
        _controller: pequiven.controller.indicator:removeValuesAction
        _format: html
    requirements:
        _format: html
        id: \d+
    methods: [POST]
    
#Select que devuelve las Gerencias de 1ra Línea para la visualización de objetivos a nivel Táctico
indicatorGerenciaFirstTactic:
    path: /indicator/indicatorGerenciaFirstTactic
    defaults:
        _controller: pequiven.controller.indicator:selectGerenciaFirstAction
        
#Select que devuelve las Gerencias de 2da Línea para la visualización de objetivos a nivel Operativo
indicatorGerenciaSecondOperative:
    path: /indicator/indicatorGerenciaSecondOperative
    defaults:
        _controller: pequiven.controller.indicator:selectGerenciaSecondListAction
        
pequiven_indicator_list_error:
    path: /listError.{_format}
    defaults:
        _controller: pequiven.controller.indicator:listErrorAction
        _format: html
    requirements:
        _format: html|json|xml
        level: 1|2|3
    methods: [GET]