pequiven_indicator:
    resource: "@PequivenSEIPBundle/Resources/config/routing/planning/indicator.yml"
    prefix:   /indicator
    
pequiven_value_indicator:
    resource: "@PequivenSEIPBundle/Resources/config/routing/planning/value_indicator.yml"
    prefix:   /value-indicator