services:
    seip.model.manager:
        class: Pequiven\SEIPBundle\Model\Admin\ModelManager
        arguments: [@doctrine]
        
    sonata.admin.formula:
        class: Pequiven\MasterBundle\Admin\FormulaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core", label: "Formula" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\Formula
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
    sonata.admin.formula.variable:
        class: Pequiven\MasterBundle\Admin\Formula\VariableAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core", label: "Variable de Formula" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\Formula\Variable
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
    sonata.admin.objetive:
        class: Pequiven\MasterBundle\Admin\Objetive\ObjetiveAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core", label: "Objetivo" }
        arguments:
            - ~
            - Pequiven\ObjetiveBundle\Entity\Objetive
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
    sonata.admin.result:
        class: Pequiven\MasterBundle\Admin\Result\ResultAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core", label: "Resultado" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\Result\Result
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.indicator.frequency_notification:
        class: Pequiven\MasterBundle\Admin\Indicator\FrequencyNotificationIndicatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador", label: "Frecuencia de notificación" }
        arguments:
            - ~
            - Pequiven\IndicatorBundle\Entity\Indicator\FrequencyNotificationIndicator
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
    sonata.admin.indicator.indicator:
        class: Pequiven\MasterBundle\Admin\IndicatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador", label: "Indicador" }
        arguments:
            - ~
            - Pequiven\IndicatorBundle\Entity\Indicator
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setModelManager, [@seip.model.manager]]