services:
    seip.model.manager:
        class: Pequiven\SEIPBundle\Model\Admin\ModelManager
        arguments: [@doctrine]
        
    sonata.admin.formula:
        class: Pequiven\MasterBundle\Admin\FormulaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core", label: "Formula" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\Formula
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setContainer, [@service_container]]
            
    sonata.admin.formula.variable:
        class: Pequiven\MasterBundle\Admin\Formula\VariableAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core", label: "Variable de Formula" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\Formula\Variable
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setContainer, [@service_container]]
    sonata.admin.objetive:
        class: Pequiven\MasterBundle\Admin\Objetive\ObjetiveAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core", label: "Objetivo" }
        arguments:
            - ~
            - Pequiven\ObjetiveBundle\Entity\Objetive
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
    sonata.admin.result:
        class: Pequiven\MasterBundle\Admin\Result\ResultAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core", label: "Resultado" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\Result\Result
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setContainer, [@service_container]]
            
    sonata.admin.indicator.frequency_notification:
        class: Pequiven\MasterBundle\Admin\Indicator\FrequencyNotificationIndicatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador", label: "Frecuencia de notificación" }
        arguments:
            - ~
            - Pequiven\IndicatorBundle\Entity\Indicator\FrequencyNotificationIndicator
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setContainer, [@service_container]]
    sonata.admin.indicator.indicator:
        class: Pequiven\MasterBundle\Admin\IndicatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador", label: "Indicador" }
        arguments:
            - ~
            - Pequiven\IndicatorBundle\Entity\Indicator
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setModelManager, [@seip.model.manager]]
            - [ setContainer, [@service_container]]
            
    sonata.admin.core.period:
        class: Pequiven\MasterBundle\Admin\PeriodAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core", label: "Periodo" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\Period
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.arrangement_program.arrangement_program:
        class: Pequiven\MasterBundle\Admin\ArrangementProgram\ArrangementProgramAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Programas de gestion", label: "Programas de gestion" }
        arguments:
            - ~
            - Pequiven\ArrangementProgramBundle\Entity\ArrangementProgram
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.arrangement_program.goal:
        class: Pequiven\MasterBundle\Admin\ArrangementProgram\GoalAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Programas de gestion", label: "Metas" }
        arguments:
            - ~
            - Pequiven\ArrangementProgramBundle\Entity\Goal
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.arrangement_program.goal_details:
        class: Pequiven\MasterBundle\Admin\ArrangementProgram\GoalDetailsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Programas de gestion", label: "Detalles de metas" }
        arguments:
            - ~
            - Pequiven\ArrangementProgramBundle\Entity\GoalDetails
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.arrangement_program.timeline:
        class: Pequiven\MasterBundle\Admin\ArrangementProgram\TimelineAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Programas de gestion", label: "Linea de tiempo" }
        arguments:
            - ~
            - Pequiven\ArrangementProgramBundle\Entity\Timeline
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]