services:
    seip.model.manager:
        class: Pequiven\SEIPBundle\Model\Admin\ModelManager
        arguments: [@doctrine]
    seip.arrangementRange.manager:
        class: Pequiven\SEIPBundle\Model\Admin\ArrangementRangeManager
        arguments: [@doctrine]
        
    sonata.admin.formula:
        class: Pequiven\MasterBundle\Admin\FormulaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador", label: "Formula" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\Formula
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setContainer, [@service_container]]
            
    sonata.admin.formula.variable:
        class: Pequiven\MasterBundle\Admin\Formula\VariableAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador", label: "Variable de Formula" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\Formula\Variable
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setContainer, [@service_container]]
            
    sonata.admin.formula.formula_detail:
        class: Pequiven\MasterBundle\Admin\Formula\FormulaDetailAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador", label: "Detalle de formula del indicador" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\Formula\FormulaDetail
            - 'PequivenMasterBundle:Admin/CRUDFormulaDetail'
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setContainer, [@service_container]]
    sonata.admin.objetive:
        class: Pequiven\MasterBundle\Admin\Objetive\ObjetiveAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Objetivo", label: "Objetivo" }
        arguments:
            - ~
            - Pequiven\ObjetiveBundle\Entity\Objetive
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
    sonata.admin.result:
        class: Pequiven\MasterBundle\Admin\Result\ResultAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Objetivo", label: "Resultado" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\Result\Result
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setContainer, [@service_container]]
            
    sonata.admin.indicator.frequency_notification:
        class: Pequiven\MasterBundle\Admin\Indicator\FrequencyNotificationIndicatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador", label: "Frecuencia de notificación" }
        arguments:
            - ~
            - Pequiven\IndicatorBundle\Entity\Indicator\FrequencyNotificationIndicator
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setContainer, [@service_container]]
    sonata.admin.indicator.indicator:
        class: Pequiven\MasterBundle\Admin\IndicatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador", label: "Indicador" }
        arguments:
            - ~
            - Pequiven\IndicatorBundle\Entity\Indicator
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setModelManager, [@seip.model.manager]]
            - [ setContainer, [@service_container]]
            
    sonata.admin.indicator.indicator_details_admin:
        class: Pequiven\MasterBundle\Admin\Indicator\IndicatorDetailsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador", label: "Detalle de Indicador" }
        arguments:
            - ~
            - Pequiven\IndicatorBundle\Entity\Indicator\IndicatorDetails
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setContainer, [@service_container]]
            
    sonata.admin.core.period:
        class: Pequiven\MasterBundle\Admin\PeriodAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core", label: "Periodo" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\Period
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setPeriodService, ['@pequiven_seip.service.period']]
            
    sonata.admin.arrangement_program.arrangement_program:
        class: Pequiven\MasterBundle\Admin\ArrangementProgram\ArrangementProgramAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Programa de gestion", label: "Programa de gestion" }
        arguments:
            - ~
            - Pequiven\ArrangementProgramBundle\Entity\ArrangementProgram
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.arrangement_program.goal:
        class: Pequiven\MasterBundle\Admin\ArrangementProgram\GoalAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Programa de gestion", label: "Metas" }
        arguments:
            - ~
            - Pequiven\ArrangementProgramBundle\Entity\Goal
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.arrangement_program.goal_details:
        class: Pequiven\MasterBundle\Admin\ArrangementProgram\GoalDetailsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Programa de gestion", label: "Detalles de metas" }
        arguments:
            - ~
            - Pequiven\ArrangementProgramBundle\Entity\GoalDetails
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.arrangement_program.timeline:
        class: Pequiven\MasterBundle\Admin\ArrangementProgram\TimelineAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Programa de gestion", label: "Linea de tiempo" }
        arguments:
            - ~
            - Pequiven\ArrangementProgramBundle\Entity\Timeline
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.arrangement_range.arrangement_range:
        class: Pequiven\MasterBundle\Admin\ArrangementRangeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Rango de gestion", label: "Rango de gestión" }
        arguments:
            - ~
            - Pequiven\ArrangementBundle\Entity\ArrangementRange
            - ~
        calls:
            - [ setTranslationDomain, [PequivenMasterBundle]]
            - [ setModelManager, [@seip.arrangementRange.manager]]
            - [ setContainer, [@service_container]]
            
    sonata.admin.line_strategic.line_strategic:
        class: Pequiven\MasterBundle\Admin\LineStrategic\LineStrategicAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Línea Estratégica", label: "Línea Estratégica" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\LineStrategic
            - ~
        calls:
            - [ setTranslationDomain, [PequivenMasterBundle]]
            - [ setContainer, [@service_container]]
    
    sonata.admin.chart:
        class: Pequiven\MasterBundle\Admin\ChartAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Tipos de Gráficos", label: "Gráficos" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\Chart
            - ~
        calls:
            - [ setTranslationDomain, [PequivenSEIPBundle]]
            - [ setContainer, [@service_container]]
            
    sonata.admin.user.complejo:
        class: Pequiven\MasterBundle\Admin\User\ComplejoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "%sonata.user.admin.groupname%" ,label_catalogue: "SonataUserBundle", label: "Complejo" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\Complejo
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.user.gerencia:
        class: Pequiven\MasterBundle\Admin\User\GerenciaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "%sonata.user.admin.groupname%" ,label_catalogue: "SonataUserBundle", label: "Gerencia de primera" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\Gerencia
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.user.gerencia_second:
        class: Pequiven\MasterBundle\Admin\User\GerenciaSecondAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "%sonata.user.admin.groupname%" ,label_catalogue: "SonataUserBundle", label: "Gerencia de segunda" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\GerenciaSecond
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.user.gerencia_group:
        class: Pequiven\MasterBundle\Admin\User\GerenciaGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "%sonata.user.admin.groupname%" ,label_catalogue: "SonataUserBundle", label: "Grupo de Gerencia" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\GerenciaGroup
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.indicator.value_indicator:
        class: Pequiven\MasterBundle\Admin\Indicator\ValueIndicatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador" ,label_catalogue: "SonataUserBundle", label: "Valor de indicador" }
        arguments:
            - ~
            - Pequiven\IndicatorBundle\Entity\Indicator\ValueIndicator
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.indicator.tag_indicator:
        class: Pequiven\MasterBundle\Admin\Indicator\TagIndicatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador" ,label_catalogue: "SonataUserBundle", label: "Etiqueta del indicador" }
        arguments:
            - ~
            - Pequiven\IndicatorBundle\Entity\Indicator\TagIndicator
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setContainer, [@service_container]]
            
    sonata.admin.indicator.type_feature_indicator:
        class: Pequiven\MasterBundle\Admin\Indicator\TypeFeatureIndicatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Indicador" ,label_catalogue: "SonataUserBundle", label: "Tipo de punto de atención" }
        arguments:
            - ~
            - Pequiven\MasterBundle\Entity\Indicator\TypeFeatureIndicator
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.quality_system.quality_system:
        class: Pequiven\MasterBundle\Admin\QualitySystem\QualitySystemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Sistemas de calidad" ,label: "Sistema de calidad" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\QualitySystem\QualitySystem
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
         
    sonata.admin.cei.cause_stop:
        class: Pequiven\MasterBundle\Admin\CEI\CauseStopAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Causa de parada" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\CauseStop
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.company:
        class: Pequiven\MasterBundle\Admin\CEI\CompanyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Empresa" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\Company
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.country:
        class: Pequiven\MasterBundle\Admin\CEI\CountryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Pais" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\Country
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.currency:
        class: Pequiven\MasterBundle\Admin\CEI\CurrencyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Moneda" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\Currency
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.location:
        class: Pequiven\MasterBundle\Admin\CEI\LocationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Sede" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\Location
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.plant:
        class: Pequiven\MasterBundle\Admin\CEI\PlantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Planta" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\Plant
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.product:
        class: Pequiven\MasterBundle\Admin\CEI\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Productos y Servicios" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\Product
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.production_line:
        class: Pequiven\MasterBundle\Admin\CEI\ProductionLineAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Linea de producto" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\ProductionLine
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.record_type:
        class: Pequiven\MasterBundle\Admin\CEI\RecordTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Tipo de registro" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\RecordType
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.sector:
        class: Pequiven\MasterBundle\Admin\CEI\SectorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Sector" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\Sector
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.sub_sector:
        class: Pequiven\MasterBundle\Admin\CEI\SubSectorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Sub sector" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\SubSector
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.type_incidence:
        class: Pequiven\MasterBundle\Admin\CEI\TypeIncidenceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Tipo de incidencia" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\TypeIncidence
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.cei.type_location:
        class: Pequiven\MasterBundle\Admin\CEI\TypeLocationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Control Estadistico e Información" ,label: "Tipo de sede" }
        arguments:
            - ~
            - Pequiven\SEIPBundle\Entity\CEI\TypeLocation
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            
    sonata.admin.configuration:
        class: Tecnocreaciones\Bundle\ToolsBundle\Admin\Configuration\ConfigurationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core",label_catalogue: "admin", label: "admin.configuration" }
        arguments:
            - ~
            - "%tecnocreaciones_tools.configuration_class.class%"
            - ~
        calls:
            - [ setTranslationDomain, [admin]]
            - [ setContainer, [@service_container]]
    sonata.admin.configuration_group:
        class: Tecnocreaciones\Bundle\ToolsBundle\Admin\Configuration\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Core",label_catalogue: "admin", label: "admin.configuration_group" }
        arguments:
            - ~
            - "%tecnocreaciones_tools.configuration_group_class.class%"
            - ~
        calls:
            - [ setTranslationDomain, [admin]]