pequiven_gerenciafirst_show:
    path: /{id}.{_format}
    defaults:
        _controller: pequiven.controller.gerenciafirst:showAction
        _format: html
    requirements:
        id: "\d+"
        _format: html|json
    methods: [GET]
    options:
        expose: true
    
pequiven_gerenciafirst_update:
    path: /{id}/update
    defaults:
        _controller: pequiven.controller.gerenciafirst:updateAction
        _sylius:
            form: pequiven_masterbundle_gerencia
    requirements:
        id: "\d+"
    methods: [GET|POST|PUT]
    
gerencia_matriz_export:
    path: /{id}/export
    defaults: { _controller: pequiven.controller.gerenciafirst:exportAction }
    requirements:
        id: "\d+"
    methods: [GET]