pequiven_pre_planning_user_index:
    path: /{period}.{_format}
    defaults:
        _controller: pequiven.controller.pre_planning_user:indexAction
        _format: html
    requirements:
        _format: html|json
        period: "\d+"
    methods: [GET]
    
pequiven_pre_planning_user_show:
    path: /{id}/show
    defaults:
        _controller: pequiven.controller.pre_planning_user:showAction
        _format: html
        id: "\d+"
    methods: [GET]
    options:
        expose: true