pequiven_pre_planning_index:
    path: /
    defaults:
        _controller: pequiven.controller.pre_planning:indexAction
    methods: [GET]
    
pequiven_pre_planning_form:
    path: /get-form
    defaults:
        _controller: pequiven.controller.pre_planning:getFormAction
        _format: html
    requirements:
        _format: html
    methods: [GET]
    
pequiven_pre_planning_get_pre_planning:
    path: /get-pre-planning.{_format}
    defaults:
        _controller: pequiven.controller.pre_planning:getPrePlanningAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    
pequiven_pre_planning_delete_pre_planning:
    path: /delete-pre-planning
    defaults:
        _controller: pequiven.controller.pre_planning:deletePrePlanningAction
        _format: json
    methods: [POST]
    
pequiven_pre_planning_return_changes:
    path: /return-changes
    defaults:
        _controller: pequiven.controller.pre_planning:returnChangesAction
        _format: json
    methods: [GET]
    
pequiven_pre_planning_start_pre_planning:
    path: /start-prep-lanning
    defaults:
        _controller: pequiven.controller.pre_planning:startPrePlanningAction
        _format: json
    methods: [GET]
    
pequiven_pre_planning_update:
    path: /update-pre-planning
    defaults:
        _controller: pequiven.controller.pre_planning:updatePrePlanningAction
        _format: json
    methods: [POST]

pequiven_pre_planning_import:
    path: /{id}/import
    defaults:
        _controller: pequiven.controller.pre_planning:importAction
        _format: json
    methods: [GET]
    options:
        expose: true