pequiven_pre_planning_index:
    path: /
    defaults:
        _controller: pequiven.controller.pre_planning:indexAction
    methods: [GET]
    
pequiven_pre_planning_form:
    path: /get-form
    defaults:
        _controller: pequiven.controller.pre_planning:getFormAction
        _format: html
    requirements:
        _format: html
    methods: [GET]
    
pequiven_pre_planning_get_pre_planning:
    path: /get-pre-planning.{_format}
    defaults:
        _controller: pequiven.controller.pre_planning:getPrePlanningAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]