
getDataChartDoughnut:
    path: /getDataChartDoughnut/{id}
    defaults:
        _controller: pequiven.controller.seipchart:getDataChartTypeDoughnutAction
        _format: json
    requirements:
        _format: "json|xml"
    methods: [GET]
    options:
        expose: true
        
getDataChartDoughnutWithVariablesFromEquation:
    path: /getDataChartDoughnutWithVariablesFromEquation/{id}
    defaults:
        _controller: pequiven.controller.seipchart:getDataChartTypeDoughnutWithVariablesFromEquationAction
        _format: json
    requirements:
        _format: "json|xml"
    methods: [GET]
    options:
        expose: true
        
getDataChartColumnLineDualAxis:
    path: /getDataChartColumnLineDualAxis/{id}
    defaults:
        _controller: pequiven.controller.seipchart:getDataChartTypeColumnLineDualAxisAction
        _format: json
    requirements:
        _format: "json|xml"
    methods: [GET]
    options:
        expose: true
        
getDataChartPieVariablesOrTags:
    path: /getDataChartPieVariablesOrTags/{id}
    defaults:
        _controller: pequiven.controller.seipchart:getDataChartTypePieVariablesOrTagsAction
        _format: json
    requirements:
        _format: "json|xml"
    methods: [GET]
    options:
        expose: true
        
getDataChartBarsArea:
    path: /getDataChartBarsArea/{id}
    defaults:
        _controller: pequiven.controller.seipchart:getDataChartBarsAreaAction
        _format: json
    requirements:
        _format: "json|xml"
    methods: [GET]
    options:
        expose: true
        
        

        
        