pequiven_planning_main:
    resource: "@PequivenSEIPBundle/Resources/config/routing/planning/main.yml"
    prefix:   /planning
    
pequiven_indicator:
    resource: "@PequivenSEIPBundle/Resources/config/routing/planning/indicator.yml"
    prefix:   /indicator