## YAML Template.
pequiven_seip_menu_home:
    path: /
    defaults: {_controller: PequivenSEIPBundle:Menu:showHome}
    methods: [GET]
    
pequiven_objetive_menu_create:
    path: /arrangement/objetive/create
    defaults: {_controller: PequivenObjetiveBundle:Objetive:create}