## YAML Template.
pequiven_seip_menu_home:
    path: /
    defaults: {_controller: PequivenSEIPBundle:Menu:showHome}
    methods: [GET]
    
pequiven_objetive_menu_create:
    path: /arrangement/objetive/create
    defaults: {_controller: PequivenObjetiveBundle:Objetive:create}

pequiven_objetive_menu_list:
    path: /arrangement_strategic/objetive/list
    defaults: {_controller: PequivenObjetiveBundle:Objetive:list}

#Lista de objetivos estratégicos
pequiven_objetive_menu_list_strategic:
    path: /arrangement_strategic/objetive/list/strategic
    defaults: 
        _controller: pequiven.controller.objetivestrategic:listAction
#Lista de objetivos tácticos
pequiven_objetive_menu_list_tactic:
    path: /arrangement_strategic/objetive/list/tactic
    defaults:
        _controller: pequiven.controller.objetivetactic:listAction
#Lista de objetivos operativos
pequiven_objetive_menu_list_operative:
    path: /arrangement_strategic/objetive/list/operative
    defaults:
        _controller: pequiven.controller.objetiveoperative:listAction
#Prueba    
pequiven_indicator_menu_list:
    path: /arrangement_strategic/indicator/list
    defaults: {_controller: PequivenIndicatorBundle:Indicator:list}
    
pequiven_objetive_menu_add_strategic:
    path: /arrangement_strategic/objetive/strategic/add
    defaults:
        _controller: pequiven.controller.objetivestrategic:createAction
    
pequiven_objetive_menu_add_tactic:
    path: /arrangement_strategic/objetive/tactic/add
    defaults:
        _controller: pequiven.controller.objetivetactic:createAction
    
pequiven_objetive_menu_add_operative:
    path: /arrangement_strategic/objetive/operative/add
    defaults:
        _controller: pequiven.controller.objetiveoperative:createAction