pequiven_seip_result_notify_arrangementprogram:
    path: /notify/arrangementprogram.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:indexAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_seip_result_notify_indicator_strategic:
    path: /notify/indicator/strategic
    defaults: 
        _controller: pequiven.controller.indicatorstrategic:listAction
    
pequiven_seip_result_notify_indicator_tactic:
    path: /notify/indicator/tactic
    defaults: 
        _controller: pequiven.controller.indicatortactic:listAction
        
pequiven_seip_result_notify_indicator_operative:
    path: /notify/indicator/operative
    defaults: 
        _controller: pequiven.controller.indicatoroperative:listAction

pequiven_seip_result_visualize_by_gerencia:
    path: /visualize/by-gerencia.{_format}
    defaults:
        _controller: pequiven.controller.result:listResultAction
        _format: html
    requirements:
        _format: html|json|xml
        level: 1|2|3
    methods: [GET]
    
pequiven_seip_result_visualize_gerencia:
    path: /visualize/gerencia/{level}/{id}.{_format}
    defaults:
        _controller: pequiven.controller.result:showMonitorAction
        _format: html
    requirements:
        _format: html|json|xml
        id: \d+
        level: 2|3
    methods: [GET]
    
pequiven_seip_result_export:
    path: /{level}/{id}/export
    defaults: { _controller: pequiven.controller.result:exportAction }
    requirements:
        id: "\d+"
    methods: [GET|POST]
    
pequiven_seip_result_export_from_chart:
    path: /{level}/{id}/export-from-chart
    defaults: { _controller: pequiven.controller.result:exportFromChartAction }
    requirements:
        id: "\d+"
    methods: [GET|POST]
    
pequiven_seip_result_visualize_objetives:
    path: /visualize/objetives/{year}/{level}.{_format}
    defaults:
        _controller: pequiven.controller.result:indexObjetivesAction
        _format: html
    requirements:
        _format: html|json|xml
        year: \d+
        level: 1|2|3
    methods: [GET]
    
pequiven_seip_result_visualize_indicators:
    path: /visualize/indicators/{year}.{_format}
    defaults:
        _controller: pequiven.controller.result:indexIndicatorsAction
        _format: html
    requirements:
        _format: html|json|xml
        year: \d+
    methods: [GET]
    
pequiven_seip_result_visualize_arrangement_programs:
    path: /visualize/arrangement-programs/{year}.{_format}
    defaults:
        _controller: pequiven.controller.result:indexArrangementProgramsAction
        _format: html
    requirements:
        _format: html|json|xml
        year: \d+
    methods: [GET]