#Devuelve el paginador con la data de los objetivos tácticos por tipo de Grupo
monitorTypeGroupList:
    path: /monitor/list/typeGroup
    defaults: 
        _controller: pequiven.controller.seipmonitor:monitorTypeGroupListAction
        _sylius:
            method: createPaginatorTypeGroup
            
#Monitor de Objetivos Operativos por Grupo de Gerencia de 1ra línea
monitorObjetiveOperative:
    path: /monitor/operative
    defaults:
        _controller: pequiven.controller.seipmonitor:displayObjetiveOperativeAction
        
monitorArrangementProgram:
    path: /monitor/arrangementProgram
    defaults:
        _controller: pequiven.controller.seipmonitor:displayArrangementProgramAction