#Devuelve el paginador con la data de los objetivos tácticos por tipo de Grupo
monitorTypeGroupList:
    path: /monitor/list/typeGroup
    defaults: 
        _controller: pequiven.controller.seipmonitor:monitorTypeGroupListAction
        _sylius:
            method: createPaginatorTypeGroup
            
#Monitor de Objetivos Operativos Agrupados por Grupo de Gerencia de 1ra línea
monitorObjetiveOperative:
    path: /monitor/operative
    defaults:
        _controller: pequiven.controller.seipmonitor:displayObjetiveOperativeAction
#Monitor de Programas de Gestión        
monitorArrangementProgram:
    path: /monitor/arrangementProgram
    defaults:
        _controller: pequiven.controller.seipmonitor:displayArrangementProgramAction
        
#Monitor de Objetivos Tácticos por Grupo de Gerencia de 1ra Línea
monitorObjetiveTacticByGroup:
    path: /monitor/tactic/{typeGroup}
    defaults:
        _controller: pequiven.controller.seipmonitor:displayObjetiveTacticByGroupAction
    methods: [GET]

#Monitor de Objetivos Operativos por Grupo de Gerencia de 1ra Línea
monitorObjetiveOperativeByGroup:
    path: /monitor/operative/{typeGroup}
    defaults:
        _controller: pequiven.controller.seipmonitor:displayObjetiveOperativeByGroupAction
    methods: [GET]
    
#Lista de Objetivos Tácticos por Gerencia de 1ra Línea
listObjetiveTacticByGroup:
    path: /list/tactic/{idGerencia}
    defaults:
        _controller: pequiven.controller.seipmonitor:listObjetiveTacticByGroupAction
    requirements:
        idGerencia: "\d+"
    methods: [GET]