pequiven_user_list:
    path: /view
    defaults:
        _controller: pequiven_seip.controller.user:listAction
    methods: [GET]

pequiven_user_aux_list:
    path: /view/aux
    defaults:
        _controller: pequiven_seip.controller.user:listAuxAction
    methods: [GET]
        
#Devuelve el paginador con la data de los usuarios
userList:
    path: /list
    defaults: 
        _controller: pequiven_seip.controller.user:userListAction
        _sylius:
            method: createPaginatorUser

userAuxList:
    path: /list/aux
    defaults: 
        _controller: pequiven_seip.controller.user:userListAuxAction
        _sylius:
            method: createPaginatorUserAux

pequiven_seip_user_show:
    path: /{id}.{_format}
    defaults:
        _controller: pequiven_seip.controller.user:showAction
        _format: html
    requirements:
        id: "\d+"
        _format: html|json
    methods: [GET]
    options:
        expose: true
    
pequiven_user_update:
    path: /{id}/update
    defaults:
        _controller: pequiven_seip.controller.user:updateAction
        _sylius:
            form: pequiven_seipbundle_user
    requirements:
        id: "\d+"
    methods: [GET|POST|PUT]
    
pequiven_user_search:
    path: /search.{_format}
    defaults:
        _controller: pequiven_seip.controller.user:searchAction
        _format: json
    requirements:
        id: "\d+"
        _format: json
    methods: GET