pequiven_value_indicator_get_form:
    path: /{idIndicator}/get-form
    defaults:
        _controller: pequiven.controller.value_indicator:getFormAction
        _format: html
    requirements:
        _format: html
    methods: [GET]
    options:
        expose: true
        
pequiven_value_indicator_calculate:
    path: /{idIndicator}/calculate.{_format}
    defaults:
        _controller: pequiven.controller.value_indicator:calculateAction
        _format: json
    requirements:
        _format: json
    methods: [POST]
    options:
        expose: true
        
pequiven_value_indicator_add:
    path: /{idIndicator}/add.{_format}
    defaults:
        _controller: pequiven.controller.value_indicator:addAction
        _format: json
    requirements:
        _format: json
    methods: [POST]
    options:
        expose: true
        
pequiven_value_indicator_show_detail:
    path: /{id}/show-detail
    defaults:
        _controller: pequiven.controller.value_indicator:showDetailAction
        _format: html
    options:
        expose: true