pequiven_meeting_create:
    path: /create/{workStudyCircle_id}
    defaults:
        _controller: pequiven.controller.meeting:createAction
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_meeting_edit:
    path: /edit/{meeting_id}
    defaults:
        _controller: pequiven.controller.meeting:editAction
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_meeting_view:
    path: /{meeting_id}
    defaults:
        _controller: pequiven.controller.meeting:viewAcction
    methods: [GET|POST]
    options:
        expose: true