pequiven_meeting_create:
    path: /create/{workStudyCircle_id}
    defaults:
        _controller: pequiven.controller.meeting:createAction
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_meeting_edit:
    path: /edit/{meeting_id}
    defaults:
        _controller: pequiven.controller.meeting:editAction
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_meeting_show:
    path: /{id}
    defaults:
        _controller: pequiven.controller.meeting:showAction
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_meeting_export_pdf:
    path: /{idmeeting}/export.{_format}
    defaults:
        _controller: pequiven.controller.meeting:exportAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_meeting_upload_form:
    path: /{idMeeting}/upload.{_format}
    defaults:
        _controller: pequiven.controller.meeting:uploadFilesAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET|POST]
    options:
        expose: true