## YAML Template.
pequiven_proposal_create:
    path: /create/{workStudyCircle_id}
    defaults:
        _controller: pequiven.controller.proposal:createAction
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_proposal_edit:
    path: /edit/{id}
    defaults:
        _controller: pequiven.controller.proposal:editAction
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_proposal_show_objetives:
    path: /objetives
    defaults:
        _controller: pequiven.controller.proposal:getObjetiveFromLineStrategicAction
    methods: [GET|POST]
    options:
        expose: true
pequiven_proposal_view_edit:
    path: /{id}/edit
    defaults:
        _controller: pequiven.controller.proposal:editAction
    methods: [GET|POST]
    options:
        expose: true