pequiven_work_study_circle_create:
    path: /create
    defaults:
        _controller: pequiven.controller.work_study_circle:createAction
        _sylius:
            form: pequiven_seipbundle_politic_workstudycircle
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_work_study_circle_member_edit:
    path: /edit-member/{idUser}
    defaults:
        _controller: pequiven.controller.work_study_circle:editWorkStudyCircleMemberAction
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_work_study_circle_show:
    path: /{id}
    defaults:
        _controller: pequiven.controller.work_study_circle:showAction
    requirements:
        id: "\d+"
    methods: [GET]

pequiven_work_study_circle_user_get_form:
    path: /{idUser}/get-form.{_format}
    defaults:
        _controller: pequiven.controller.user:getFormAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET]
    options:
        expose: true
        
pequiven_work_study_circle_add_others_members:
    path: /{idWorkStudyCircle}/addOthersMembers.{_format}
    defaults:
        _controller: pequiven.controller.work_study_circle:addOthersMembersAction
        _format: html
    requirements:
        _format: html|jso
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_work_study_circle_export_pdf:
    path: /{idWorkStudyCircle}/export.{_format}
    defaults:
        _controller: pequiven.controller.work_study_circle:exportAction
        _format: html
    requirements:
        _format: html|json
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_work_study_circle_general:
    path: /view
    defaults:
        _controller: pequiven.controller.work_study_circle:viewAction               
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_work_study_circle_list:
    path: /list.{_format}
    defaults:
        _controller: pequiven.controller.work_study_circle:listAction  
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_work_study_circle_coordinators:
    path: /coordinators.{_format}
    defaults: 
        _controller: pequiven_seip.controller.user:searchCoordinatorAction
        _format: json
    requirements:
        _format: "json|xml"
    methods: [GET]
    options:
        expose: true   
