pequiven_work_study_circle_create:
    path: /create
    defaults:
        _controller: pequiven.controller.work_study_circle:createAction
        _sylius:
            form: pequiven_seipbundle_politic_workstudycircle
    methods: [GET|POST]
    options:
        expose: true
        
pequiven_work_study_circle_show:
    path: /{id}
    defaults:
        _controller: pequiven.controller.work_study_circle:showAction
    requirements:
        id: "\d+"
    methods: [GET]
pequiven_work_study_circle_list:
    path: /list
    defaults:
        _controller: pequiven.controller.work_study_circle:listAction
        _sylius:
            form: pequiven_seipbundle_politic_workstudycircle
    methods: [GET|POST]
    options:
        expose: true