## YAML Template.
pequiven_indicator_add_strategic_from_objetive:
    path: /arrangement_strategic/indicator/strategic/addFromObjetive
    defaults: {_controller: PequivenIndicatorBundle:IndicatorStrategic:createFromObjetive}
    
pequiven_indicator_add_tactic_from_objetive:
    path: /arrangement_strategic/indicator/tactic/addFromObjetive
    defaults: {_controller: PequivenIndicatorBundle:IndicatorTactic:createFromObjetive}

pequiven_indicator_add_operative_from_objetive:
    path: /arrangement_strategic/indicator/oeprative/addFromObjetive
    defaults: {_controller: PequivenIndicatorBundle:IndicatorOperative:createFromObjetive}

pequiven_indicator_register_redirect:
    path: /arrangement_strategic/indicator/registerRedirect
    defaults: {_controller: PequivenIndicatorBundle:Indicator:registerRedirect}
    
#Muestra el Número de Referencia del indicador estratégico a crear
displayRefIndicatorStrategic:
    path: /arrangement_strategic/indicator/displayRefIndicatorStrategic
    defaults: {_controller: PequivenIndicatorBundle:IndicatorStrategic:displayRefIndicator}
    
#Muestra el Número de Referencia del indicador estratégico a crear a partir de un objetivo estratégico
displayRefIndicatorStrategicFromObjetive:
    path: /arrangement_strategic/indicator/displayRefIndicatorStrategicFromObjetive
    defaults: {_controller: PequivenIndicatorBundle:IndicatorStrategic:displayRefIndicatorFromObjetive}

#Muestra el Número de Referencia del indicador táctico a crear
displayRefIndicatorTactic:
    path: /arrangement_strategic/indicator/displayRefIndicatorTactic
    defaults: {_controller: PequivenIndicatorBundle:IndicatorTactic:displayRefIndicator}
    
#Muestra el Número de Referencia del indicador estratégico a crear a partir de un objetivo táctico
displayRefIndicatorTacticFromObjetive:
    path: /arrangement_strategic/indicator/displayRefIndicatorTacticFromObjetive
    defaults: {_controller: PequivenIndicatorBundle:IndicatorTactic:displayRefIndicatorFromObjetive}

#Muestra el Número de Referencia del indicador operativo a crear
displayRefIndicatorOperative:
    path: /arrangement_strategic/indicator/displayRefIndicatorOperative
    defaults: {_controller: PequivenIndicatorBundle:IndicatorOperative:displayRefIndicator}
    
#Muestra el Número de Referencia del indicador estratégico a crear a partir de un objetivo operativo
displayRefIndicatorOperativeFromObjetive:
    path: /arrangement_strategic/indicator/displayRefIndicatorOperativeFromObjetive
    defaults: {_controller: PequivenIndicatorBundle:IndicatorOperative:displayRefIndicatorFromObjetive}

#Select que devuelve los Indicadores Estratégicos de acuerdo a la Línea Estratégica seleccionada
select_indicatorStrategicFromRefParent:
    path: /arrangement_strategic/indicator/select_indicatorStrategicFromRefParent
    defaults: {_controller: PequivenIndicatorBundle:IndicatorStrategic:selectIndicatorStrategicFromRefParent}
    
#Select que devuelve los Indicadores Tácticos de acuerdo a la Línea Estratégica seleccionada
select_indicatorTacticFromRefParent:
    path: /arrangement_strategic/indicator/select_indicatorTacticFromRefParent
    defaults: {_controller: PequivenIndicatorBundle:IndicatorTactic:selectIndicatorTacticFromRefParent}
    
#Select que devuelve los Indicadores Operativos de acuerdo a la Línea Estratégica seleccionada
select_indicatorOperativeFromRefParent:
    path: /arrangement_strategic/indicator/select_indicatorOperativeFromRefParent
    defaults: {_controller: PequivenIndicatorBundle:IndicatorOperative:selectIndicatorOperativeFromRefParent}