Pequiven\IndicatorBundle\Entity\Indicator\EvolutionIndicator\EvolutionAction:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        createdAt:
            expose: true
            groups: [api_list]
        updatedAt:
            expose: true
            groups: [api_details]
        createdBy:
            expose: true
            groups: [api_details]