Pequiven\IndicatorBundle\Entity\Indicator\EvolutionIndicator\EvolutionCause:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        createdAt:
            expose: true
            groups: [api_list]
        updatedAt:
            expose: true
            groups: [api_details]
        causes:
            expose: true
            groups: [api_list]
        valueOfindicator:
            expose: true
            groups: [api_list]