Pequiven\ArrangementProgramBundle\Entity\ArrangementProgram:
    constraints:
        - Pequiven\ArrangementProgramBundle\Validator\Constraints\MaximumGoalResponsible:
                groups: [base]
        - Pequiven\ArrangementProgramBundle\Validator\Constraints\LevelRolesResponsible:
                groups: [base]
    properties:
        period:
            - NotNull:
                groups: [base]
#        categoryArrangementProgram:
#            - NotNull:
#                groups: [categoryArrangementProgram]
        tacticalObjective:
            - NotNull:
                groups: [tacticalObjective]
        operationalObjective:
            - NotNull:
                groups: [operationalObjective]
#        process:
#            - NotNull:
#                groups: [categoryArrangementProgram]
        type:
            - NotNull:
                groups: [base]
    getters:
        validTimeLine:
            - "True":
                message: pequiven.validators.arrangement_program.incorrect_weight
                groups: [base]
        validResponsibles:
            - "True":
                message: pequiven.validators.arrangement_program.incorrect_responsibles
                groups: [base]
        validResponsiblesGoals:
            - "True":
                message: pequiven.validators.goals_details.min_responsibles
                groups: [base]

Pequiven\ArrangementProgramBundle\Entity\ArrangementProgramTemplate:
    properties:
        description:
            - NotNull: ~
            
Pequiven\ArrangementProgramBundle\Entity\Goal:
    properties:
        name:
            - NotNull:
                groups: [base]
        startDate:
            - NotNull:
                groups: [base]
        endDate:
            - NotNull:
                groups: [base]
#        responsible:
#            - NotNull:
#                message: pequiven.validators.arrangement_program.goal.responsible_person
#                groups: [base]
        weight:
            - NotNull:
                groups: [base]
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
                groups: [base]
                
Pequiven\ArrangementProgramBundle\Entity\GoalDetails:
    properties:
        januaryPlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        januaryReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        februaryPlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        februaryReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        marchPlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        marchReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        aprilPlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        aprilReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        mayPlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        mayReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        junePlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        juneReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        julyPlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        julyReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        augustPlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        augustReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        septemberPlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        septemberReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        octoberPlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        octoberReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        novemberPlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        novemberReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        decemberPlanned:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value
        decemberReal:
            - Range:
                min: 0
                minMessage: pequiven.validators.goals_details.min_value
                max: 100
                maxMessage: pequiven.validators.goals_details.max_value