pequiven_seip_arrangementprogram_index:
    path: /.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:indexAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_arrangementprogram_create:
    path: /{type}/create
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:createAction }
    requirements:
        type: 1|2|3
    methods: [GET|POST]
    
pequiven_seip_arrangementprogram_show:
    path: /{id}
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:showAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_revised:
    path: /{id}/revised
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:revisedAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_approved:
    path: /{id}/approved
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:approvedAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_send_to_review:
    path: /{id}/send-to-review
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:sendToReviewAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_update:
    path: /{id}/update
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:updateAction }
    requirements:
        id: "\d+"
    methods: [GET|PUT|POST]
    
arrangementprogram_delete:
    path: /{id}
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:deleteAction }
    requirements:
        id: "\d+"
    methods: [DELETE]