pequiven_seip_arrangementprogram_index:
    path: /.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:indexAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_seip_arrangementprogram_list_template:
    path: /list-template.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:listTemplateAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_seip_arrangementprogram_assigned:
    path: /assigned.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:assignedAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_arrangementprogram_create:
    path: /{type}/create
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:createAction }
    requirements:
        type: 1|2
    methods: [GET|POST]
    options:
        expose: true
    
pequiven_seip_arrangementprogram_show:
    path: /{id}
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:showAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_revised:
    path: /{id}/revised
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:revisedAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_send_to_draft:
    path: /{id}/send-to-draft
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:sendToDraftAction }
    requirements:
        id: "\d+"
    methods: [POST]
    
arrangementprogram_return_to_review:
    path: /{id}/return-to-review
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:returnToReviewAction }
    requirements:
        id: "\d+"
    methods: [POST]
    
arrangementprogram_approved:
    path: /{id}/approved
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:approvedAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_reject:
    path: /{id}/reject
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:rejectAction }
    requirements:
        id: "\d+"
    methods: [POST]
    
arrangementprogram_send_to_review:
    path: /{id}/send-to-review
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:sendToReviewAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_add_observation:
    path: /{id}/add-observation.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:addObservationAction
        _format: json
    requirements:
        id: "\d+"
        _format: json|xml
    methods: [POST]
    
arrangementprogram_update:
    path: /{id}/update
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:updateAction }
    requirements:
        id: "\d+"
    methods: [GET|PUT|POST]
    
arrangementprogram_delete:
    path: /{id}
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:deleteAction }
    requirements:
        id: "\d+"
    methods: [DELETE]
    
arrangementprogram_export:
    path: /{id}/export
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:exportAction }
    requirements:
        id: "\d+"
    methods: [GET]